### PR TITLE
Fix nullptr deref in unsafe code

### LINKED ISSUE #76: Lan Discovery segfault
When running `$ cargo run --example dht_node`

```
Starting program: /home/humbug/zetox/target/debug/examples/dht_node 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff69ff700 (LWP 25611)]
[New Thread 0x7ffff63ff700 (LWP 25612)]
[New Thread 0x7ffff5dff700 (LWP 25613)]
[New Thread 0x7ffff57ff700 (LWP 25614)]
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([125, 237, 186, 21, 65, 189, 85, 24, 226, 60, 155, 217, 29, 118, 253, 5, 234, 67, 113, 199, 74, 13, 217, 251]), payload: [231, 125, 48, 121, 172, 244, 85, 240, 54, 170, 147, 106, 183, 87, 71, 69, 128, 26, 136, 200, 225, 140, 143, 26, 216, 151] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([139, 241, 179, 179, 95, 133, 79, 59, 229, 252, 46, 221, 122, 137, 147, 157, 216, 65, 94, 219, 204, 64, 143, 160]), payload: [215, 123, 23, 74, 183, 63, 237, 66, 78, 129, 78, 192, 192, 112, 250, 21, 104, 197, 20, 103, 168, 32, 50, 159, 139, 255] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([40, 29, 28, 143, 170, 224, 191, 18, 6, 16, 7, 201, 203, 180, 240, 78, 11, 57, 173, 78, 85, 56, 195, 136]), payload: [87, 64, 179, 28, 187, 46, 104, 118, 191, 40, 161, 20, 177, 51, 213, 26, 148, 60, 216, 224, 132, 16, 13, 45, 119, 5] })
lan_wakeup

Thread 4 "tokio-runtime-w" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5dff700 (LWP 25613)]
0x00005555557e8e03 in get_if_addrs::getifaddrs_posix::sockaddr_to_ipaddr::haaf65eefab8dbaee (sockaddr=0x0)
    at /home/humbug/.cargo/registry/src/github.com-1ecc6299db9ec823/get_if_addrs-0.5.0/src/lib.rs:163
163	        let sa_family = u32::from(unsafe { *sockaddr }.sa_family);
```

```
   │130         // get broadcast addresses for host's network interfaces                                                   │
   │131         fn get_ipv4_broadcast_addrs() -> Vec<IpAddr> {                                                             │
  >│132             let ifs = get_if_addrs::get_if_addrs().expect("no network interface");                                 │
   │133             ifs.iter().filter_map(|interface|                                                                      │
   │134                 match interface.addr {                                                                             │
   │135                     IfAddr::V4(ref addr) => addr.broadcast,                                                        │
   │136                     _ => None,                                                                                     │
   │137             })                                                                                                     │
   │138             .map(|ipv4|                                                                                            │
   │139                 IpAddr::V4(ipv4)                                                                                   │
   │140             ).collect()                                                                                            │
   │141         }       
```

### PR DESCRIPTION
**Pull request by kpp**
Fixes https://github.com/tox-rs/tox/issues/76

cc @m-cat @ustulation @Viv-Rajkumar

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @maqi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by kpp** [comment]
Git blame: https://github.com/maidsafe/get_if_addrs/pull/30/files#diff-b4aea3e418ccdb71239b96952d9cddb6R163

LoL

**Comment by 0x7CFE** [comment]
This code compromises the very idea of safety in Rust.

The whole function must be `unsafe` because pointer casts are safe. You could create a pointer to some random or uninitialized data structure in safe Rust and pass it into that function, invoking undefined behaviour.

Therefore this potential threat must be advertised above, so `unsafe` for the function is a must. Otherwise, users of this function would have no idea, that something dangerous may happen.

If the idea is to create an API where pointers generated by this library are trusted (and so can be dereferenced without unsafe), an opaque type wrapping the raw pointer should be used.

FYI, [`NonNull` was stabilized]( https://doc.rust-lang.org/std/ptr/struct.NonNull.html) in Rust 1.25.

**Review by ustulation — APPROVED** [review]

**Comment by ustulation** [comment]
Ah well spotted :+1: 

Also agree with [this](https://github.com/maidsafe/get_if_addrs/pull/33#issuecomment-377694754).

cc @m-cat @nbaksalyar

**Comment by kpp** [comment]
Please create a new release with hotfix.

**Pull request merged**
