### PR TITLE
Updated to work with libc 0.2

### PR DESCRIPTION
**Pull request by dhylands**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/get_if_addrs/24)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @canndrew (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by ustulation** [comment]
hey @dhylands - thanks for the PR. It fails Windows CI currently. Can you pls see if you can sort that ? Should be good for review after that.

**Comment by dhylands** [comment]
Added a commit to address the Windows side of things. I don't have any IPv6 equipment to test things, so it would be good to take special attention to this change (from a review perspective):
https://github.com/maidsafe/get_if_addrs/pull/24/commits/23632fd3473d42d3dc5710fc7855c5979b10ce50#diff-b4aea3e418ccdb71239b96952d9cddb6L163 and this change: https://github.com/maidsafe/get_if_addrs/pull/24/commits/6c8df39dbab6fba186941227a069e0a0c2f8fc62#diff-b4aea3e418ccdb71239b96952d9cddb6L361

My understanding is that those are stored in network (big-endian) order, so I'm pretty sure I rewrote it correctly.

**Comment by canndrew** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/get_if_addrs/24)_

**Comment by canndrew** [comment]
Looks good @dhylands. Thanks for the PR, new package version in the works.

**Pull request merged**
